---
title: "Practise Assignment"
author: "Vishaylin J. Mahadeo"
date: "August 30, 2016"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE ,
                      warning = FALSE , 
                      cache = TRUE ,
                      fig.align = 'center' ,
                      fig.path = 'figure/', 
                      fig.height = 8, 
                      fig.width = 8, 
                      fig.ext = 'png')
library(dplyr)
library(readr)
library(tidyr)
```

## Hello Octocat
I love Octocat. She's the coolest cat in town.
! [](https://dl.dropboxusercontent.com/u/11805474/painblogr/biostats/images/octocat.png)

```{r quick_look}
#load data set
data("anscombe")

#column titles
names(anscombe)

#show dimensions of data set rows vs. columns
dim(anscombe)

#show first 6 rows
head(anscombe, 6)

#show last 6 rows
tail(anscombe, 6)

#summary statistics for each column
summary(anscombe)
```

```{r xy_plot}
#load data set
data("anscombe")

#scatter plot (with axis titles, red, and squares)
graph <- plot(x = anscombe$x1, y = anscombe$y1,
     main = 'Figure 1: Scatter plot of anscombe showing x1 vs. y1',
     xlab = 'Anscombe (x1)',
     ylab = 'Anscombe (y1)',
     pch = 15 ,
     col = 2 ,
     lty = 2)

#regression line
regline <- lm(y1 ~ x1, data = anscombe)
abline(regline)
```
```{r data_import}
#load data set
df_analgesic <- read_csv('analgesic.csv')
```

```{r data_summary}
#dimensions of data set
dim(df_analgesic)

#names of column titles
names(df_analgesic)

#first 6 rows of data set
head(df_analgesic)

#last 6 rows of data set
tail(df_analgesic)

#summary statistics for each column
summary(df_analgesic)
```

```{r data_tidy}
#gather data from wide to long format
gathered <- gather(data = df_analgesic ,
                   key = measurements ,
                   value = data, Measurement_1:Measurement_3)

#group by individuals
by_id <- group_by(gathered, ID)
by_id

#summarise and calculate mean
report <- summarize(by_id, mean(data))
report
```
